version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:337a12f4c9da661e9f373c49470668bbcae19fa1accd52ffef301041746b365e

node_8: &node_8
  docker:
    - image: node:8@sha256:5aebe186c00da3308c8fde5b3a246d1927a56947a1b51f5c4308b7318adf74f4

node_next: &node_next
  docker:
    - image: node:latest@sha256:5ea9b2d04e1da959087d93289bdcfa5011c3a173bddf3eaf98553676d28b8f63

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]
  deliver:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies_deliver
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: v1-dependencies_deliver
      - run: $(yarn bin)/semantic-release-github --preset @hbetts/config
  deploy:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies_deploy
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: v1-dependencies_deploy
      - run: $(yarn bin)/npm-publish-git-tag

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
      - deliver:
          filters:
            branches:
              only: master
          requires:
            - node_6_test_plan
            - node_8_test_plan
          context: github-interaction
      - deploy:
          filters:
            tags:
              only: /.+/
          requires:
            - deliver
          context: package-publishing

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/6d8f0cad1cb033a36cf4
