version: 2

node_4: &node_4
  docker:
    - image: node:4@sha256:632f9021e36b39891f1442df6cbcfe399144f6bef4f5af4aaaf481db0734e73c

node_6: &node_6
  docker:
    - image: node:6@sha256:4f280f2855b3c860e14faa007db941b6e88c3a467b94401bc5a593086c2105ee

node_8: &node_8
  docker:
    - image: node:8@sha256:8329de7ecb8324d8b598f0979c5458c9f3b2f6b4a7eb6046e5ac6e99573b279d

node_next: &node_next
  docker:
    - image: node:latest@sha256:9e5a048068aaf9205ae7769701cfa5f77ab125a10eda4ac8905d5c14aef9902e
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies_yarn_latest
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: dependencies_yarn_latest
    - run: yarn test && ($(yarn bin)/codecov || echo "Codecov did not collect coverage reports")

yarn_latest: &yarn_latest
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies_yarn_latest
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: dependencies_yarn_latest
    - run: yarn test && ($(yarn bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_4_yarn_latest:
    <<: [*node_4, *yarn_latest]
  node_6_yarn_latest:
    <<: [*node_6, *yarn_latest]
  node_8_yarn_latest:
    <<: [*node_8, *yarn_latest]
  node_next:
    <<: [*node_next]
  release:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_release
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_release
      - run: $(yarn bin)/semantic-release-github
  publish:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_publish
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_publish
      - run: $(yarn bin)/npm-publish-git-tag

workflows:
  version: 2
  build:
    jobs:
      - node_4_yarn_latest
      - node_6_yarn_latest
      - node_8_yarn_latest
      - node_next
      - release:
          filters:
            branches:
              only: master
          requires:
          - node_4_yarn_latest
          - node_6_yarn_latest
          - node_8_yarn_latest
      - publish:
          filters:
            tags:
              only: /.+/
          requires:
            - release
