version: 2.1

orbs:
  release-workflows: hutson/library-release-workflows@4.3.3

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:6@sha256:337a12f4c9da661e9f373c49470668bbcae19fa1accd52ffef301041746b365e
  node_8_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:8@sha256:5aebe186c00da3308c8fde5b3a246d1927a56947a1b51f5c4308b7318adf74f4
  node_10_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:10@sha256:94c90424c2a44ea72daaed746540fb39a44c56310d530b2760281a457b0e6846
  node_next_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:latest@sha256:5ea9b2d04e1da959087d93289bdcfa5011c3a173bddf3eaf98553676d28b8f63

workflows:
  version: 2

  build_and_test:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_10_test_plan
      - node_next_test_plan
      - release-workflows/deliver:
          context: github-interaction
          filters:
            branches:
              only: master
          requires:
            - node_6_test_plan
            - node_8_test_plan
            - node_10_test_plan

  deploy:
    jobs:
      - release-workflows/npm-deploy:
          context: package-publishing
          filters:
            tags:
              # Match only semantically valid semver tags - Authored by David Fichtmueller - https://github.com/semver/semver/issues/232#issue-48635632
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
