version: 2.1

orbs:
  release-workflows: hutson/library-release-workflows@4.3.3

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:6@sha256:d4973c8036658a8b43534e5ace8a2ae9e3867832d45582b5d6a0105a03ff8502
  node_8_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:8@sha256:7b65413af120ec5328077775022c78101f103258a1876ec2f83890bce416e896
  node_10_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:10
  node_next_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:latest@sha256:4c42c2b2f908cdd43e833047e38ac553dfed79a51b0583bcd4550c60d35bf383

workflows:
  version: 2

  build_and_test:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_10_test_plan
      - node_next_test_plan
      - release-workflows/deliver:
          context: github-interaction
          filters:
            branches:
              only: master
          requires:
            - node_6_test_plan
            - node_8_test_plan
            - node_10_test_plan

  deploy:
    jobs:
      - release-workflows/npm-deploy:
          context: package-publishing
          filters:
            tags:
              # Match only semantically valid semver tags - Authored by David Fichtmueller - https://github.com/semver/semver/issues/232#issue-48635632
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
