version: 2

node_4: &node_4
  docker:
    - image: node:4@sha256:9afac44734b937476ed9656e6ecf64cde4c271025228a9939d2bde76d426169d

node_6: &node_6
  docker:
    - image: node:6@sha256:6c882b9ae7b8569c2e5f9fe30b43387fafad8bb280cf797d669010a895c65dea

node_8: &node_8
  docker:
    - image: node:8@sha256:d1a97c68e06df6ab34974996fe5479d417316c97d6b333704453fac3549cc08f

node_next: &node_next
  docker:
    - image: node:latest@sha256:788512049d7b55da1fe6ca38c7a575d0dabdee29765fd7375f5bdee29f6235c1
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies_yarn_latest
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: dependencies_yarn_latest
    - run: yarn test && ($(yarn bin)/codecov || echo "Codecov did not collect coverage reports")

yarn_latest: &yarn_latest
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies_yarn_latest
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: dependencies_yarn_latest
    - run: yarn test && ($(yarn bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_4_yarn_latest:
    <<: [*node_4, *yarn_latest]
  node_6_yarn_latest:
    <<: [*node_6, *yarn_latest]
  node_8_yarn_latest:
    <<: [*node_8, *yarn_latest]
  node_next:
    <<: [*node_next]
  release:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_release
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_release
      - run: $(yarn bin)/semantic-release-github
  publish:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_publish
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_publish
      - run: $(yarn bin)/npm-publish-git-tag

workflows:
  version: 2
  build:
    jobs:
      - node_4_yarn_latest
      - node_6_yarn_latest
      - node_8_yarn_latest
      - node_next
      - release:
          filters:
            branches:
              only: master
          requires:
          - node_4_yarn_latest
          - node_6_yarn_latest
          - node_8_yarn_latest
      - publish:
          filters:
            tags:
              only: /.+/
          requires:
            - release
