version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:6ed17656f6b15e5d97c2a7a6b73b76a237dffb6e0c0ccc78b52f98c5083889e3

node_8: &node_8
  docker:
    - image: node:8@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda

node_next: &node_next
  docker:
    - image: node:latest@sha256:2cda73dd26369c2ec69130ddda6f83ff4980fd6fc8e73b5e670a7670d4c86ba0

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]
  deliver:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_deliver
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_deliver
      - run: $(yarn bin)/semantic-release-github
  deploy:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies_deploy
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: dependencies_deploy
      - run: $(yarn bin)/npm-publish-git-tag

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
      - deliver:
          filters:
            branches:
              only: master
          requires:
            - node_6_test_plan
            - node_8_test_plan
          context: github-interaction
      - deploy:
          filters:
            tags:
              only: /.+/
          requires:
            - deliver
          context: npm-interaction

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/6d8f0cad1cb033a36cf4
